name: On Pull Request

on: [pull_request]

env:
  PORT: 3001
  ENVIRONMENT: development
  DB_TYPE: postgres
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: bull
  DB_PWD: bull
  DB_NAME: bull
  DB_LOGGING: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js (v18.15)
      uses: actions/setup-node@v3
      with:
        node-version: 18.15
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Building app
      run: npm run build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [build]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: bull
          POSTGRES_DB: bull
          POSTGRES_PASSWORD: bull
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
        - 5432:5432

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js (v18.15)
      uses: actions/setup-node@v3
      with:
        node-version: 18.15
        cache: npm

    - name: Install Dependencies
      run: npm install

    - name: Run Test
      run: npm run test

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: |
          ${{ github.workspace }}/coverage
