version: "3.9"

services:

    database:
        image: postgres
        container_name: 'bull-back-db'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=bull
            - POSTGRES_PASSWORD=bull
            - POSTGRES_DB=bull
        volumes:
            - ./.volumes/postgres:/var/lib/postgresql
        networks:
            - default

    api:
        build:
            context: .
            dockerfile: ./infrastructure/docker/node/Dockerfile
        container_name: 'bull-back-api'
        ports:
            - '3001:3001'
            - '9229:9229'
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
        networks:
            - default
